platform :ios, '8.0'
target "Coding_iOS" do

pod 'ReactiveCocoa', :git => 'https://github.com/zhao0/ReactiveCocoa.git', :tag => '2.5.2'
pod 'AFNetworking'
pod 'SDWebImage'
pod 'FMDB'
pod 'MJExtension'
pod 'Masonry'
pod 'TTTAttributedLabel'
pod 'MBProgressHUD', '0.9'
pod 'SVProgressHUD'
pod 'IQKeyboardManager'

end

